--drop table EZ_USER;
CREATE TABLE EZ_USER
(
	USER_ID    VARCHAR(20) NOT NULL comment '유저ID',
	USER_NM    VARCHAR(20) NOT NULL comment '사용자명',
	USER_PWD   VARCHAR(100) NOT NULL comment '비밀번호',
	USE_YN     VARCHAR(1) DEFAULT 'Y' NOT NULL comment '사용여부'
) comment = '사용자'
;
ALTER TABLE EZ_USER ADD(
	CONSTRAINT EZ_USER_PK PRIMARY KEY (USER_ID));


--drop table ACL_AUTH;
CREATE TABLE ACL_AUTH
(
	AUTH_CD   VARCHAR (20) NOT NULL comment '권한관리',
	AUTH_NM   VARCHAR (50) comment '명칭',
	AUTH_DC   VARCHAR (200) comment '설명',
	REG_DT    VARCHAR (14) comment '등록일',
	MODI_DT   VARCHAR (14) comment '수정일'
) comment = '권한관리'
;
ALTER TABLE ACL_AUTH ADD(
	CONSTRAINT EZ_AUTH PRIMARY KEY (AUTH_CD));



--drop table ACL_RESOURCE;
CREATE TABLE ACL_RESOURCE
(
	RESOURCE_CD    VARCHAR (50) NOT NULL comment '리소스코드',
	RESOURCE_NM    VARCHAR (100) comment '명칭',
	RESOURCE_DC    VARCHAR (200) comment '설명',
	RESOURCE_URL   VARCHAR (300) comment '패턴',
	REG_DT         VARCHAR (20) comment '등록일',
	MODI_DT        VARCHAR (20) comment '수정일'
) comment = '리소스관리'
;
ALTER TABLE ACL_RESOURCE ADD(
	CONSTRAINT PK_EZ_ROLE PRIMARY KEY (RESOURCE_CD));



--drop table ACL_USER_AUTH;
CREATE TABLE ACL_USER_AUTH
(
	USER_ID   VARCHAR (20) NOT NULL comment '사이트별 사용자키',
	AUTH_CD   VARCHAR (20) comment '권한코드',
	REG_DT    VARCHAR (14) comment '등록일',
	MODI_DT   VARCHAR (14) comment '수정일',
	CONSTRAINT `FK_ACL_AUTH_TO_ACL_USER_AUTH` FOREIGN KEY (AUTH_CD) REFERENCES ACL_AUTH(AUTH_CD),
	CONSTRAINT `FK_EZ_USER_TO_ACL_USER_AUTH` FOREIGN KEY (USER_ID) REFERENCES EZ_USER(USER_ID)
) comment = '사용자권한관리'
;
ALTER TABLE ACL_USER_AUTH ADD(
	CONSTRAINT EZ_USER_AUTH PRIMARY KEY (USER_ID));



--drop table ACL_AUTH_RESOURCE;
CREATE TABLE ACL_AUTH_RESOURCE
(
	AUTH_CD       VARCHAR (20) NOT NULL comment '권한코드',
	RESOURCE_CD   VARCHAR (50) NOT NULL comment '리소스코드',
	REG_DT        VARCHAR (14) comment '등록일',
	MODI_DT       VARCHAR (14) comment '수정일',
	CONSTRAINT `FK_AUTH_TO_AUTH_RESOURCE` FOREIGN KEY (AUTH_CD) REFERENCES ACL_AUTH (AUTH_CD),
	CONSTRAINT `FK_RESOURCE_TO_AUTH_RESOURCE` FOREIGN KEY (RESOURCE_CD) REFERENCES ACL_RESOURCE (RESOURCE_CD)
) comment = '권한별 리소스관리'
;
ALTER TABLE ACL_AUTH_RESOURCE ADD(
	CONSTRAINT PK_ACL_AUTH_RESOURCE PRIMARY KEY (AUTH_CD, RESOURCE_CD));


--drop table ACL_AUTH_HIERARCHY;
CREATE TABLE ACL_AUTH_HIERARCHY
(
	SEQ              int NOT NULL,
	PARENT_AUTH_CD   VARCHAR (20) NOT NULL comment '계층 부모',
	CHILD_AUTH_CD    VARCHAR (20) NOT NULL comment '계층 자식'
) comment = '권한 계층 관리'
;

ALTER TABLE ACL_AUTH_HIERARCHY ADD(
	CONSTRAINT ACL_AUTH_HIERARCHY_PK PRIMARY KEY (SEQ));

ALTER TABLE ACL_AUTH_HIERARCHY ADD(
	CONSTRAINT `ACL_AUTH_HIERARCHY_UK` UNIQUE (PARENT_AUTH_CD, CHILD_AUTH_CD));

